spring:
  application:
    name: m2i-bank

  ### DATASOURCE ###
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  ### JPA ###
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

### SERVER ###
server:
  port: 8090

### JWT ###
jwt:
  secret: ${JWT_SECRET}




